name: Kaperski CI/CD Pipeline

on:  
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: opencart-core
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: opencart-core
          IMAGE_TAG: latest
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Deploy to Private EC2 via AWS Systems Manager
        run: |

          IMAGE="777315623538.dkr.ecr.us-east-1.amazonaws.com/opencart-core:latest"
          
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=OpenCart-Server" \
            --comment "Deploy latest OpenCart Docker image" \
            --parameters 'commands=[
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 777315623538.dkr.ecr.us-east-1.amazonaws.com",
            "docker pull $IMAGE",
      
            "docker stop opencart-app || true",
            "docker rm opencart-app || true",
      
            "docker create --name opencart-init $IMAGE",
            "mkdir -p /tmp/opencart-image",
            "docker cp opencart-init:/var/www/html/image/. /tmp/opencart-image/",
            "cp -rn /tmp/opencart-image/* /var/www/html/image/",
            "docker rm opencart-init",
            "rm -rf /tmp/opencart-image",
      
            "docker run -d --name opencart-app --restart unless-stopped -p 80:80 -v /var/www/html/image:/var/www/html/image $IMAGE",
      
            "docker image prune -f",
            "docker images"
            ]' \
            --region us-east-1
